package de.wevsvirus.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Objects;

@DynamoDBTable(tableName = "Aerzte")
public class ArztModel {

    private String uid;
    private String phoneNumber;
    private String plz;
    private int freeTimeSlots = 0;
    private boolean isCoronaTester = false;

    public ArztModel() {
        // empty constructor for spring.data
    }

    public ArztModel(String phoneNumber) {
        this.uid = null;
        this.phoneNumber = phoneNumber;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    @DynamoDBAttribute
    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @DynamoDBAttribute
    public boolean isCoronaTester() {
        return isCoronaTester;
    }

    public void setCoronaTester(boolean coronaTester) {
        isCoronaTester = coronaTester;
    }

    @DynamoDBAttribute
    public String getPlz() {
        return plz;
    }

    public void setPlz(String plz) {
        this.plz = plz;
    }

    @DynamoDBAttribute
    public int getFreeTimeSlots() {
        return freeTimeSlots;
    }

    public void setFreeTimeSlots(int freeTimeSlots) {
        this.freeTimeSlots = freeTimeSlots;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ArztModel arztModel = (ArztModel) o;
        return phoneNumber.equals(arztModel.phoneNumber);
    }

    @Override
    public int hashCode() {
        return Objects.hash(phoneNumber);
    }

    @Override
    public String toString() {
        return "Arzt{phoneNumber='" + phoneNumber + '\'' +
                ", isCoronaTester=" + isCoronaTester +
                '}';
    }
}
